apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  selector:
    matchLabels:
      app: userservice
  replicas: 1
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: user-service
          image: zakaria469980/testuserfoots:latest
          ports:
            - containerPort: 5117
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 5117 # externl port
      targetPort: 80 # internal port
      name: http-port
    - protocol: TCP
      port: 7117 # externl port
      targetPort: 443 # internal port
      name: https-port
  # LoadBalancer to expose service externally, Should use nodePort or ClusterIp when Ingress is setup
  type: ClusterIP



