# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: userservice-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: userservice
#   template:
#     metadata:
#       labels:
#         app: userservice
#     spec:
#       containers:
#         - name: userservice
#           image: zakaria469980/userservice:latest
#           env:
#             - name: POSTGRES_HOST
#               value: postgres-service   # Use the PostgreSQL service name
#             - name: POSTGRES_PORT
#               value: "5432"
#             - name: POSTGRES_DB
#               value: mydatabase        # Use the PostgreSQL database name
#             - name: POSTGRES_USER
#               value: myuser            # Use the PostgreSQL username
#             - name: POSTGRES_PASSWORD
#               value: mypassword        # Use the PostgreSQL password

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-service-clusterip
# spec:
#   type: ClusterIP
#   selector:
#     app: userservice
#   ports:
#     - name: userservice
#       protocol: TCP
#       port: 80
#       targetPort: 80







# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-service
# spec:
#   type: NodePort
#   selector:
#     app: userservice
#   ports:
#     - name: userservice
#       protocol: TCP
#       port: 80
#       targetPort: 80



apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: zakaria469980/uuserservice:latest
          ports:
            - containerPort: 5117
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: userservice  # Adjusted to match the correct label
  ports:
    - protocol: TCP
      port: 5117
      targetPort: 80
      name: http-port
    - protocol: TCP
      port: 7117
      targetPort: 443
      name: https-port
    - name: postgres 
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer




