apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-and-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice-and-postgres
  template:
    metadata:
      labels:
        app: userservice-and-postgres
    spec:
      containers:
        - name: userservice-backend
          image: zakaria469980/foottweetsuser:latest
          ports:
            - containerPort: 5117
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice-and-postgres
  template:
    metadata:
      labels:
        app: userservice-and-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-and-postgres-service
spec:
  selector:
    app: userservice-and-postgres
  ports:
    - name: http-port
      protocol: TCP
      port: 5117
      targetPort: 5117
    - name: https-port
      protocol: TCP
      port: 7117
      targetPort: 443
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
