apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-backend
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: zakaria469980/footuserserviceeee:latest
          ports:
            - containerPort: 5117
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-database
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:            
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5117 # externl port
      targetPort: 80 # internal port
      name: http-port
    - protocol: TCP
      port: 7117 # externl port
      targetPort: 443 # internal port
      name: https-port
    - name: postgres 
      protocol: TCP
      port: 5432
      targetPort: 5432
  # LoadBalancer to expose service externally, Should use nodePort or ClusterIp when Ingress is setup
  type: LoadBalancer



