apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 1   # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: zakaria469980/userservice:latest
          env:
            - name: POSTGRES_HOST
              value: postgres-service   # Use the PostgreSQL service name
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: mydatabase        # Use the PostgreSQL database name
            - name: POSTGRES_USER
              value: myuser            # Use the PostgreSQL username
            - name: POSTGRES_PASSWORD
              value: mypassword        # Use the PostgreSQL password


---
apiVersion: v1
kind: Service
metadata:
  name: user-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
    - name: userservice
      protocol: TCP
      port: 80
      targetPort: 80







# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-service
# spec:
#   type: NodePort
#   selector:
#     app: userservice
#   ports:
#     - name: userservice
#       protocol: TCP
#       port: 80
#       targetPort: 80



