apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 1   # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: serservice
          image: zakaria469980/userservice:latest
          ports:
          - containerPort: 80   # Adjust the port number as needed
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer   # Use NodePort, ClusterIP, or LoadBalancer based on your setup
